language: node_js
node_js:
- 10.15.3
cache: yarn
branches:
  only:
  - master
  - "/^v?([0-9]+)\\.([0-9]+)\\.([0-9]+)$/"
  - "/^feature.*/"
  - "/^chore.*/"
  - "/^bug.*/"
  - "/^revert.*/"
script:
- npm run test:travis
before_install:
- npm config set spin false
- export PATH="./bin:$PATH"
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH="$HOME/.yarn/bin:./bin:$PATH"
